#config.py

# TOGGLE TEST MODE WITH TRUE OR FALSE
TEST_MODE_ACTIVATED = False

# TEST MODE USES FILENAME_META_TST AND PRODUCTION MODE USES  FILENAME_META_PRD
FILENAME_META_PRD = "dla.csv"
FILENAME_META_TST = "dla_short_test.csv"

# SPLITS BIG META DATA CSV IN SMALL PARTS
# DEFINE THE NUMBER OF ROWS FOR EACH CHUNK.
# ZERO DISABLES META DATA FILE SPLITTING
CSV_SPILT_FILE_ROWS = 1000

# ASK YES OR NO BEFORE PROCESSING THE NEXT CHUNK
PROMPT_AFTER_CHUNK = False

# ENABLED OR DISABLES CLEANING THE OUTPUT FOLDER WHEN THE PROGRAM STARTS.
# SETTING THIS TO TRUE ACTIVATES THE CLEANUP AND THE PRIOR BACKUP OF THE DATA.
# BACKED-UP DATA WILL BE MOVED TO THE BACKUP FOLDER WITH A TIMESTAMP.
CLEAN_OUTPUT_FOLDER_AT_STARTUP = False

# OUTPUT FOLDER FOR RESULT FILES
OUTPUT_DIR = "output"

# DEFAULT VALUE IF NO YEAR VALUE WAS FOUND
NOT_FOUND_RETURN_VALUE = "0"

# ENABLES AI-ASSISTED IDENTIFICATION OF YEARS WITHIN THE STRING.
# THE AI PRODUCES MORE RESULTS THAN THE RULE-BASED EXTRACTION, BUT IT CAN ALSO LEAD TO INCORRECT
# YEARS DUE TO MISINTERPRETATION BY THE AI.
ENABLE_AI_PROCESS = True

# CONSOLE COLORS
GREEN = "\033[92m"
RESET = "\033[0m"

